@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Chapter 1: case in progress
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" case-open
if errorlevel 1 pause
