@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Chapter 1: the recap card
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" recap
if errorlevel 1 pause
