@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Developer Mode (jump anywhere)
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" dev-menu
if errorlevel 1 pause
