@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Fight: the Unpicked (boss)
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" battle-boss
if errorlevel 1 pause
