@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Fight: Alarm and stealth
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" battle-stealth
if errorlevel 1 pause
