@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Fight: a Rag-wraith
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" battle-wraith
if errorlevel 1 pause
