@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Fight: the Empty Coat
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" battle-coat
if errorlevel 1 pause
