@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Minigame: the mirrored seam
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" stitch-mirror
if errorlevel 1 pause
