@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Minigame: The Long Way Round
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" crossing
if errorlevel 1 pause
