@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Minigame: Seam & Stitch (4x4)
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" stitch-big
if errorlevel 1 pause
