@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Minigame: Testimony
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" testimony
if errorlevel 1 pause
