@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Minigame: Seam & Stitch
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" stitch
if errorlevel 1 pause
