@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Minigame: The Unpicking
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" lattice
if errorlevel 1 pause
