@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Minigame: Patch the Ward
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" ward
if errorlevel 1 pause
