@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title On the Prowl (loadout)
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" loadout
if errorlevel 1 pause
