@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Prowl: An Empty Coat
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" prowl-coat
if errorlevel 1 pause
