@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Prowl: The Garden Route
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" prowl-garden
if errorlevel 1 pause
