@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Prowl: Press On economy
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" press-on
if errorlevel 1 pause
