@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title Prowl: one hit from the Court
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" last-life
if errorlevel 1 pause
