@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title State: the Coat with the Swat kit
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" coat-finale
if errorlevel 1 pause
