@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title State: worn mid-prowl
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" worn
if errorlevel 1 pause
