@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title State: over-levelled
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" rich
if errorlevel 1 pause
