@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title State: first boot
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" fresh-start
if errorlevel 1 pause
