@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title State: Moonlight-heavy deck
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" moonlight
if errorlevel 1 pause
