@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title State: just finished the prologue
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" post-prologue
if errorlevel 1 pause
