@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title The Case Board (empty)
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" case-board
if errorlevel 1 pause
