@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title The Magpie Exchange
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" exchange
if errorlevel 1 pause
