@echo off
rem Generated by play.ps1 -Install. Edit parts.json, not this file.
title The Prologue (from the top)
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" prologue
if errorlevel 1 pause
