<#
.SYNOPSIS
  Launch one part of The Nine Lives of Ashcat without playing to it.

.DESCRIPTION
  Every part runs through the game's component runner (--scene <spec>),
  which builds a THROWAWAY profile. Nothing launched from here can read or
  write the real save, so you can try anything without losing your place.

  Note for editors: this file is deliberately plain ASCII and is saved with
  a UTF-8 BOM. Windows PowerShell 5.1 decodes BOM-less files as ANSI and
  turns any dash or curly quote into mojibake, which is a parse error, not
  a cosmetic one (CLAUDE.md law 4).

.EXAMPLE
  .\play.ps1                 # pick from a menu
  .\play.ps1 mantel          # launch by name
  .\play.ps1 -List           # show every part
  .\play.ps1 -Install        # regenerate the double-clickable shims in apps\
#>
[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [string] $Part,
    [switch] $List,
    [switch] $Install
)

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$repo = Split-Path -Parent $here
$gameDir = Join-Path $repo 'game'

# .NET reads UTF-8; Get-Content in PS 5.1 would decode the manifest's
# punctuation as ANSI and print mojibake.
function Get-Parts {
    $manifest = Join-Path $here 'parts.json'
    if (-not (Test-Path $manifest)) { throw "missing manifest: $manifest" }
    return ([IO.File]::ReadAllText($manifest) | ConvertFrom-Json).parts
}

# Godot lives outside the repo and is not everyone's business to have in the
# same place. $env:GODOT wins; otherwise try the project's documented path.
function Get-Godot {
    if ($env:GODOT -and (Test-Path $env:GODOT)) { return $env:GODOT }
    $known = @(
        'C:\Users\yurim\tools\godot\Godot_v4.4.1-stable_win64_console.exe',
        (Join-Path $env:LOCALAPPDATA 'Godot\Godot_v4.4.1-stable_win64_console.exe')
    )
    foreach ($candidate in $known) { if (Test-Path $candidate) { return $candidate } }
    $onPath = Get-Command godot -ErrorAction SilentlyContinue
    if ($onPath) { return $onPath.Source }
    throw 'Godot not found. Set $env:GODOT to the Godot executable and try again.'
}

function Show-Parts {
    param($parts)
    $group = ''
    foreach ($p in $parts) {
        if ($p.group -ne $group) {
            $group = $p.group
            Write-Host ''
            Write-Host ('  ' + $group) -ForegroundColor DarkYellow
        }
        Write-Host ('    {0,-20} {1}' -f $p.name, $p.title)
        Write-Host ('    {0,-20} {1}' -f '', $p.about) -ForegroundColor DarkGray
    }
    Write-Host ''
}

function Invoke-Part {
    param($part)
    $godot = Get-Godot
    Write-Host ''
    Write-Host ('  ' + $part.title) -ForegroundColor Yellow
    Write-Host ('  ' + $part.about) -ForegroundColor DarkGray
    Write-Host '  (throwaway profile: your real save is untouched)' -ForegroundColor DarkGray
    Write-Host ''
    & $godot --path $gameDir -- --scene $part.spec
}

$parts = Get-Parts

if ($Install) {
    # One double-clickable shim per part. Regenerated wholesale so a part
    # renamed or dropped from the manifest does not leave a dead icon behind.
    $appsDir = Join-Path $here 'apps'
    if (Test-Path $appsDir) {
        Get-ChildItem (Join-Path $appsDir '*.cmd') | Remove-Item -Force
    } else {
        New-Item -ItemType Directory -Path $appsDir | Out-Null
    }
    foreach ($p in $parts) {
        # Filenames stay to a conservative set: anything else becomes a dash.
        $safe = ($p.title -replace '[^A-Za-z0-9 _()\-]', '-').Trim()
        $body = @(
            '@echo off',
            'rem Generated by play.ps1 -Install. Edit parts.json, not this file.',
            ('title ' + $p.title),
            ('powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\play.ps1" ' + $p.name),
            'if errorlevel 1 pause'
        ) -join "`r`n"
        $path = Join-Path $appsDir ($safe + '.cmd')
        [IO.File]::WriteAllText($path, $body + "`r`n", (New-Object Text.UTF8Encoding $false))
    }
    Write-Host ('installed ' + $parts.Count + ' launchers in ' + $appsDir) -ForegroundColor Green
    return
}

if ($List) {
    Show-Parts $parts
    return
}

if ($Part) {
    $match = $parts | Where-Object { $_.name -eq $Part }
    if (-not $match) {
        Write-Host ("unknown part '" + $Part + "'. Available:") -ForegroundColor Red
        Show-Parts $parts
        exit 1
    }
    Invoke-Part $match
    return
}

# No argument: pick from a numbered menu.
Write-Host ''
Write-Host '  The Nine Lives of Ashcat - try a part' -ForegroundColor Yellow
$group = ''
for ($i = 0; $i -lt $parts.Count; $i++) {
    if ($parts[$i].group -ne $group) {
        $group = $parts[$i].group
        Write-Host ''
        Write-Host ('  ' + $group) -ForegroundColor DarkYellow
    }
    Write-Host ('    {0,2}. {1}' -f ($i + 1), $parts[$i].title)
}
Write-Host ''
$choice = Read-Host '  number (or blank to quit)'
if ([string]::IsNullOrWhiteSpace($choice)) { return }
$index = 0
if (-not [int]::TryParse($choice, [ref] $index) -or $index -lt 1 -or $index -gt $parts.Count) {
    Write-Host '  not a part.' -ForegroundColor Red
    exit 1
}
Invoke-Part $parts[$index - 1]
